# Generated by Django 5.1.5 on 2025-03-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_cuser_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfirmEmail",
        ),
    ]
