# Generated by Django 5.1.5 on 2025-02-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="thumbnail",
            field=models.FileField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
